# Generated by Django 5.1.4 on 2025-05-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_logo', models.FileField(default='default.png', upload_to='coreapp/testimonials/company_logos/%Y/%m/%d/')),
                ('designation', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('user_image', models.ImageField(default='default.png', upload_to='coreapp/testimonials/user_images/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
