# Generated by Django 5.1.4 on 2024-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('fajr_icon', models.ImageField(upload_to='prayer_times/')),
                ('fajr_start', models.TimeField()),
                ('fajr_iqamah_time', models.TimeField(blank=True, null=True)),
                ('fajr_end', models.TimeField(blank=True, null=True)),
                ('dhuhr_icon', models.ImageField(upload_to='prayer_times/')),
                ('dhuhr_start', models.TimeField()),
                ('dhuhr_iqamah_time', models.TimeField(blank=True, null=True)),
                ('dhuhr_end', models.TimeField(blank=True, null=True)),
                ('asr_icon', models.ImageField(upload_to='prayer_times/')),
                ('asr_start', models.TimeField()),
                ('asr_iqamah_time', models.TimeField(blank=True, null=True)),
                ('asr_end', models.TimeField(blank=True, null=True)),
                ('maghrib_icon', models.ImageField(upload_to='prayer_times/')),
                ('maghrib_start', models.TimeField()),
                ('maghrib_iqamah_time', models.TimeField(blank=True, null=True)),
                ('maghrib_end', models.TimeField(blank=True, null=True)),
                ('isha_icon', models.ImageField(upload_to='prayer_times/')),
                ('isha_start', models.TimeField()),
                ('isha_iqamah_time', models.TimeField(blank=True, null=True)),
                ('isha_end', models.TimeField(blank=True, null=True)),
                ('jumuah_icon', models.ImageField(upload_to='prayer_times/')),
                ('jumuah_start', models.TimeField()),
                ('jumuah_iqamah_time', models.TimeField(blank=True, null=True)),
                ('jumuah_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
