# Generated by Django 5.1.4 on 2024-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayertime',
            name='asr_icon',
            field=models.ImageField(default='prayer_times/default.webp', upload_to='prayer_times/'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='dhuhr_icon',
            field=models.ImageField(default='prayer_times/default.webp', upload_to='prayer_times/'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='fajr_icon',
            field=models.ImageField(default='prayer_times/default.webp', upload_to='prayer_times/'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='isha_icon',
            field=models.ImageField(default='prayer_times/default.webp', upload_to='prayer_times/'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='jumuah_icon',
            field=models.ImageField(default='prayer_times/default.webp', upload_to='prayer_times/'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='jumuah_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='maghrib_icon',
            field=models.ImageField(default='prayer_times/default.webp', upload_to='prayer_times/'),
        ),
    ]
