# Generated by Django 5.1.4 on 2024-12-25 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayertimes', '0002_alter_prayertime_asr_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertime',
            name='sunrise_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayertime',
            name='sunrise_icon',
            field=models.ImageField(default='prayer_times/default.webp', upload_to='prayer_times/'),
        ),
        migrations.AddField(
            model_name='prayertime',
            name='sunrise_iqamah_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayertime',
            name='sunrise_start',
            field=models.TimeField(default=datetime.datetime(2024, 12, 25, 22, 23, 52, 231543, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
