# Generated by Django 5.1.4 on 2024-12-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidertranslation',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
