# Generated by Django 5.1.4 on 2025-05-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pricingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdemo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
