# Generated by Django 5.1.4 on 2024-12-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
