# Generated by Django 5.1.4 on 2025-05-21 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutiontranslation',
            old_name='content',
            new_name='banner_content',
        ),
        migrations.RenameField(
            model_name='solutiontranslation',
            old_name='title',
            new_name='banner_title',
        ),
        migrations.AddField(
            model_name='solutioncategory',
            name='image',
            field=models.ImageField(default='default.png', upload_to='solution/images/'),
        ),
        migrations.AddField(
            model_name='solutioncategorytranslation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solutiontranslation',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solutiontranslation',
            name='secondary_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(default='default.png', upload_to='solution/images/'),
        ),
    ]
