# Generated by Django 5.1.4 on 2025-06-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_rename_content_solutiontranslation_banner_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.SmallIntegerField(choices=[(0, 'Project'), (1, 'Role'), (2, 'Firm')]),
        ),
    ]
