name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install dependencies
      run: sudo apt-get install -y rsync

    - name: Clean server directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "rm -rf /home/psiy/*"

    - name: Sync files to server
      run: |
        rsync -avz --delete --exclude '.git/' --exclude 'node_modules/' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/psiy/

    - name: Run migrations and restart services
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
        cd /home/psiy/
        source venv/bin/activate
        python manage.py makemigrations
        python manage.py migrate
        sudo systemctl restart gunicorn
        sudo systemctl reload nginx
        EOF
