# Generated by Django 5.1.4 on 2025-05-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_usages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
