# Generated by Django 5.1.4 on 2025-06-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productusage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.SmallIntegerField(choices=[(0, 'Preconstruction'), (1, 'Execution'), (2, 'Construction Intelligence'), (3, 'Collaboration Hub'), (4, 'Quality and Safety'), (5, 'Integrations')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
    ]
