# Generated by Django 5.1.4 on 2025-08-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_type_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.SmallIntegerField(choices=[(0, 'Preconstruction'), (1, 'Execution'), (2, 'Construction Intelligence'), (3, 'Collaboration Hub'), (4, 'Integrations')]),
        ),
    ]
